Fix container build by resolving conflict between nodejs and nsolid.
The container build fails at nsolid installation because nodejs is already
installed:

Error:
 Problem: problem with installed package nodejs-1:22.19.0-2.module+el9.7.0+23475+0a960596.x86_64
...
Error: building at STEP "RUN curl -fsSL https://rpm.nodesource.com/setup_22.x | bash - && yum install -y nsolid && yum clean all": while running runtime: exit status 1

I assume we intentionally want to use NSolid as an alternative to nodejs.
As both packages do not co-exist with each other, we need to remove nodejs before
installing NSolid.

Signed-off-by: hseipp <20093686+hseipp@users.noreply.github.com>